jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    # metadata:
    #    auto_detection: true
    #    directories:
    #        any-name:
    #            namespace_prefix: "App\\Controller"
    #            path: "@JMSSerializerBundle"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
